version: '2.4'
services:
  app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    expose:
      - "5000"
    volumes:
      - .:/app
      - $DATASETS_PATH:/datasets
    links:
      - db
    networks:
      - frontend
      - backend   


  db:
    image: mongo:latest
    command: mongod --bind_ip_all
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - $DB_PATH:/data/db
    networks:
      - backend


  webserver:
    container_name: webserver
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - frontend


networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
